app = "cgm-remote-monitor-mtxl5a"

[build]
  image = "nightscout/cgm-remote-monitor:latest"
  
[[services]]
internal_port = 1337
protocol = "tcp"
[[services.ports]]
  port = 80
  handlers = ["http"]
[[services.ports]]
  port = 443
  handlers = ["tls", "http"][http_service]
