app = "Zevi-Nightscout"  # replace with app name from Fly.io

[build]
  image = "nightscout/cgm-remote-monitor:latest"
  
[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
